name: cnctsun
version: '1.0'
summary: C&C Tiberian Sun is a real-time strategy game.
description: |
 C&C Tiberian Sun is a real-time strategy video game developed by Westwood Studios and released in 1999. The main storyline follows the second major war between the Global Defense Initiative (GDI) of the United Nations, and the global terrorist organization known as the Brotherhood of Nod. The story takes place 30 years after the GDI had won the First Tiberium War in Command & Conquer.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-i386

apps:
  cnctsun:
    command: |
      bin/sommelier "$(find $WINEPREFIX/ -type f \( -name 'Launcher.exe' -o -name 'TSMPLauncher.exe' \) 2>/dev/null)"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
      INSTALL_URL_TS: "http://tore29.com/tsins/TSinstaller.exe" # cnctsun full game setup
      INSTALL_URL_CNC: "https://downloads.cncnet.org/TiberianSun_Online_Installer.exe" # cnctsun multiplayer only setup
      MONO_URL: "https://dl.winehq.org/wine/wine-mono/4.7.1/wine-mono-4.7.1.msi"
      TRICKS: "dotnet20"
      VIRTDESKTOP: 0
      LC_ALL: "C.UTF-8"
    plugs:
      - wine-platform-plug
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio
      - wayland
      - x11
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-platform/bin/winetricks prefix="$WINEPREFIX"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - wayland
      - x11

parts:
  cnctsun:
    plugin: dump
    source: snap/scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'sommelier': bin/
